#!/usr/bin/env bash
# This script lists the content of the current directory in a list format 
# and displays only the part of the name after the first dash.

for file in $(ls); do
    # Skip hidden files
    if [[ "$file" != .* ]]; then
        # Get the part of the name after the first dash
        name_after_dash=$(echo "$file" | cut -d'-' -f2-)
        echo "$name_after_dash"
    fi
done

