#!/usr/bin/env bash
# Display all processes for all users, including those without a TTY
# Format output in a user-friendly way and show process hierarchy
ps -eH -o user,pid,%cpu,%mem,vsz,rss,tty,stat,start,time,command

