#!/usr/bin/env bash
# This script writes "I am alive!" to /tmp/my_process every 2 seconds indefinitely.

# manage_my_process: writes "I am alive!" every 2 seconds
while true; do
    echo "I am alive!" >> /tmp/my_process
    sleep 2
done

